themesberg/flowbite-svelte

src/lib/tabs/InteractiveTabs.svelte

The active class was used on the wrong element. Therefore the active tab was not highlighted.

Fixed active styles in InteractiveTabs.svelte

---

package.json
src/lib/forms/FloatingLabelInput.svelte
src/lib/forms/Iconinput.svelte
src/lib/forms/Input.svelte
src/lib/forms/Select.svelte
src/lib/forms/SingleCheckbox.svelte
src/lib/forms/Textarea.svelte
src/lib/forms/Toggle.svelte
src/lib/utils/generateId.js

This ensures that labels are associated with inputs if no id is passed, and that ids will be unique on forms that have nested components where names may be re-used

feat: default input ids to sequentially-generated strings

---

src/lib/modals/ExtraLargeModal.svelte
src/lib/modals/LargeModal.svelte
src/lib/modals/MediumModal.svelte
src/lib/modals/SignInModal.svelte
src/lib/modals/SmallModal.svelte

This also fixes clicking the sides of the modal to close.

fix: enable scrolling in modals (fixes #23)

---

src/app.css
src/lib/buttons/Button.svelte
src/lib/forms/Input.svelte

1. Fixed labels having margin when there is no label.
2. Buttons should not have any margin, it should be up to the user to add that.

Margin Fixes

---

src/lib/tables/TableSearch.svelte

let the user bind the search box `inputValue` for their own filter logic
Ref: https://github.com/themesberg/flowbite-svelte/issues/117
Closes # 117
let the user bind the search box `inputValue` for their own filter logic
syntax
If your branch is behind the upstream master, I will have difficulties to merge the request. Please fetch the latest version of the branch:
```sh
```
or
```sh
```

Make TableSearch flexible for user defined filter

---

src/lib/buttons/Button.svelte
src/routes/buttons/index.md

Removed the horrible `gradientMonochrome` and `gradientDuoTone` parameters. Replaced with simple `gradient: boolean` flag.

Buttons - proposal for simplified API.

---

src/lib/badges/Badge.svelte
src/routes/badges/index.md
src/routes/props/Badge.json

Added property rounded that set 'rounded-full' class to the badge to support icon only use-case.
Minor fixes:
- setting class on badge is possible now
- justify-center added for content alignment

feature: icons only badges

---

src/lib/alerts/Alert.svelte
src/routes/alerts/index.md

Fix to lack of color of the Close buttons in the alerts.
This is fix for #139

fix: alerts dismissable button color

---

src/lib/avatar/Dot.svelte
src/lib/dropdowns/Dropdown.svelte
src/lib/dropdowns/DropdownHeader.svelte
src/lib/dropdowns/DropdownItem.svelte
src/lib/tooltips/Tooltip.svelte
src/lib/utils/CloseButton.svelte
src/routes/dropdowns/index.md

Covering #144 
Extended examples of dropdowns from Flowbite.com. Done with the minimal touch of Dropdown.svelte implemtation.
Couple of side changes were needed to be able to run those examples notably: tooltip - clickoutside changed.
Very verbose usage of checkboxes made the examples really long. I wish it were a shorter API to checkboxes.

feature: dropdowns extended examples

---

src/lib/forms/Checkbox.svelte
src/lib/forms/Label.svelte
src/lib/forms/Radio.svelte
src/lib/forms/Toggle.svelte
src/routes/forms/checkbox.md
src/routes/forms/radio.md

Form buttons: Radio, Checkbox, Toggle rewritten again. 
I can't make the svelte component 'inheritance' work well so needed another code structure.
Svelte compiler is strict in checking the binding and does not allow `bind:checked` to `input type="radio"`.
On the other hand there's a known svelte bug of not properly handling `bind:group` for `input type="checkbox"` when it's wrapped in the custom component.
The above prevents in practice the usage of one file all input types support.
This PR adds as well a follow `disable` to the label component so it is not needed to handle that in checkbox or radio.
Toggle is just a special case of checkbox and is implemented as `<Checkbox custom={true} ...`.
`on:click` is not omitted this time.

Form buttons

---

src/lib/dropdowns/Dropdown.svelte
src/lib/forms/SimpleSearch.svelte
src/routes/dropdowns/index.md
src/routes/forms/checkbox.md
src/routes/forms/radio.md

- Added [Radio in dropdown](https://flowbite.com/docs/forms/radio/#radio-in-dropdown) and [Checkbox in dropdown](https://flowbite.com/docs/forms/checkbox/#checkbox-dropdown)
- Format adjustments to Search example in Dropdown
- Dropdown - floating menu added Radio/Checkbox prefixes to sections.
- Some other polishing here and there
Flowbite introduces anomaly of dark colors when forms are put on another component. This is visible when Checkbox or Radio is put on Dropdown for example. That's why I've added `tinted` property to those.
I needed to add `tinted` property to `SimpleSearch` for the same reason.

forms-buttons: missing examples and tuning

---

src/lib/dropdowns/Dropdown.svelte
src/lib/forms/Checkbox.svelte
src/lib/forms/Radio.svelte
src/lib/forms/SimpleSearch.svelte
src/lib/forms/Toggle.svelte
src/routes/dropdowns/index.md

Form buttons again.
Found a way to get rid of `tinted` props. The slightly different dark rendering will be triggered by the parent component usage of `setContext('background',true)`. This is now added to `Dropdown` component.

feat: form buttons tinted removed

---

src/routes/__layout.svelte
src/routes/index.svelte
src/routes/pages/getting-started.md
src/routes/pages/how-to-contribute.md

Fixed small typo in `Getting Started` and `How to Contribute` pages of the documentation.

Fixed more typos and website layout

---

src/lib/megamenu/MegaMenu.svelte
src/lib/navbar/NavDropdown.svelte

Fix for mega menu centre problem.
https://github.com/themesberg/flowbite-svelte/pull/184#issuecomment-1197731636
In fact it was an issue of NavDropdown not MegaMenu.
I have modified the column number in small screen views as well. Please check if ok.
If your branch is behind the upstream master, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
```sh
```
or
```sh
```

fix: megamenu centered in small screen

---

src/lib/modals/Modal.svelte
src/lib/utils/focusTrap.js

Focus trap for `Modal` component.
When modal is shown the focus moves only within the modal.
Implemented as shown here:  https://uxdesign.cc/how-to-trap-focus-inside-modal-to-make-it-ada-compliant-6a50f9a70700

feat: focus trap for modals

---

src/lib/alerts/Alert.svelte
src/routes/alerts/index.md

Alerts with list example added.
However **I don't understand** why Flowbite.com does not follow it's own coloring standard.
All alerts examples use the flowing colors:
`bg-blue-100 text-blue-700 dark:bg-blue-200 dark:text-blue-800`
and the newly added example introduces 
`bg-blue-50 text-blue-900`
**Why??** Setting color name on that alert has no sense at all.

feat: alerts with lists

---

src/lib/dropdowns/Dropdown.svelte
src/lib/tooltips/Tooltip.svelte
src/routes/dropdowns/index.md

Closes #217 
- `Tooltip` variable `open` changed to be exported
- `Dropdown` - export `open` variable bind to `Tooltip`
- doc added example how to control dropdown via `open` var

fix: dropdown open/close api

---

src/lib/dropdowns/DropdownItem.svelte

Fixes #244 . I don't know the reason why `|stopPropagation` is necessary, but it breaks client-side navigation if there is a link inside the DropdownItem.

Prevent DropdownItem to force full page-refresh if it contains a link

---

src/lib/index.ts
src/lib/toolbar/Toolbar.svelte
src/lib/toolbar/ToolbarButton.svelte
src/lib/toolbar/ToolbarGroup.svelte
src/routes/props/Toolbar.json
src/routes/props/ToolbarButton.json
src/routes/toolbar/+page.md

Components:
- `Toolbar` - not part of the Flowbite.com but presented in `Textarea` examples.
- `ToolbarButton` - button designed to but put on the toolbar, but we can migrate `CloseButton` to be a specific `ToolbarButton`
- `ToolbarGroup` - for groupping many `ToolbarButton`
In docs, I have re-used the modified `Textarea` examples here to demonstrate the simplified implementation.
Should we add that to the framework?
Only `lib/toolbar/*.svelte` and `routes/toolbar/+page.md`  added. To see the docs you need to manually navigate to `/toolbar`

feat: toolbar

---

src/lib/utils/Popper.svelte

Closes #245 
Just using visible as a class does not remove the space it needs from the dom. Well, it somehow does for some reason, but not before half a second or so, which causes half a second of CLS.
Using "hidden" removes it from the dom, but breaks the animation.
Solution: use "absolute". Keeps the animation & removed the space from the dom => no CLS anymore.
This is a simple fix, but I'd still be interested to know why that space from the dom is removed after like half-a-second? Is it adding some kind of hidden element after a delay or so to keep the animation? Because if so, that could be removed

Fix CLS in DropDown / Popper

---

src/lib/avatar/Avatar.svelte
src/lib/dropdowns/Dropdown.svelte
src/lib/dropdowns/DropdownItem.svelte
src/lib/popover/Popover.svelte
src/lib/tooltips/Tooltip.svelte
src/lib/utils/Popper.svelte
src/routes/dropdowns/+page.md
src/routes/popover/+page.md
src/routes/tooltips/+page.md

`Popper` re-written. **Breaking changes**
Features:
- decouple content from trigger - connection made via css query specified in `triggeredBy` parameter
- multiple trigger elements possible - `Popper` can be re-used from different places in the document
- use of the `fade` animation function from svelte instead of `transition-opacity`
- use of svelte `if` directive instead of `visible opacity` classes
- `createPopper` called only when content is open
Can you please do some testing before merge? 
@AlessioGr can you check the behavior with SSR rendering? 
`Dropdown`, `Tooltip`, `Popover` - old API left and some docs require further updates.

Popper again

---

src/lib/alerts/Alert.svelte
src/lib/cards/Card.svelte
src/lib/dropdowns/Dropdown.svelte
src/lib/list-group/List.svelte
src/lib/modals/Modal.svelte
src/lib/popover/Popover.svelte
src/lib/toasts/Toast.svelte
src/lib/utils/Frame.svelte
src/lib/utils/Popper.svelte
src/routes/toasts/+page.md

Abstract component frame, base for `Alert, Toast, Dropdown, Card, Modal, GroupList`
- common colors of background and text
- common behaviour - disappearance
- common styling - borders, shadow, rounding
- as a side effect brings colors to `Dropdown`, `Card`, `List`
- no changes to any existing examples
Current solution of introduction `customBgClass`, `customTextClass` is not really good as you can mix classes and set text classes to `customBgClass` attribute with the same result.
I have started to use 'none' as color to remove coloring classes and be free to add your custom classes in the standard `class` attribute.
```svelte
<Frame color="red" />
<Frame color="none" class"bg-yellow-100 text-red-500 />
```

feat: frame abstraction

---

src/lib/dropdowns/Dropdown.svelte
src/lib/popover/Popover.svelte
src/lib/utils/Popper.svelte
src/routes/dropdowns/+page.md

Fix for #256 
Popper can:
- be open/close programmatically
- be open at init
- be triggered by the previous sibling if no `triggeredBy` elements found

fix: programatic popper open merged

---

src/routes/tabs/+page.md

📑 Description
-  Setup was importing from $lib instead of 'flowbite-svelte'

wrong input path

---

src/lib/dropdowns/Dropdown.svelte
src/lib/dropdowns/DropdownItem.svelte
src/lib/navbar/NavLi.svelte
src/lib/popover/Popover.svelte
src/lib/tooltips/Tooltip.svelte
src/lib/utils/Chevron.svelte
src/lib/utils/Frame.svelte
src/lib/utils/Popper.svelte
src/routes/dropdowns/+page.md
src/routes/popover/+page.md
src/routes/tooltips/+page.md

This is a first step towards separating the dropdown button from `Dropdown.svelte` component.
New component created in `utils`: `Chevron.svelte`, which contains the logic of attaching the appropriate chevron to text.
Examples of its usage are in `dropdowns` docs (first example, multi-level and navbar dropdown).
Separation of button from dropdown is in line with latest `Popper` changes, and gives a user the total control over the triggering component.
I have left still the `label` option in `Dropdown.svelte` for the backward compatibility and until all examples are updated.

feat: dropdown button

---

src/lib/toasts/Toast.svelte
src/routes/toast/+page.md

Fix for #269 
Transitions passed as svelte functions rather then string value.

fix: toast transitions

---

src/lib/dropdowns/DropdownItem.svelte
src/lib/forms/Radio.svelte
src/lib/utils/Popper.svelte
src/routes/dropdown/+page.md

`Dropdown` corrections.
- `<li>` added `a` element to avoid setting tabindex
- tabindex removed from dropdown docs
- add names to radio groups
- correction of strange bug with radio dropdowns
- removal `style='position: absolute` from `Popper` as that was causing the bug above
- removed `label=` from all dropdown examples

fix: dropdowns tweaks

---

src/lib/alerts/Alert.svelte
src/lib/avatar/Avatar.svelte
src/lib/cards/Card.svelte
src/lib/drawer/Drawer.svelte
src/lib/dropdowns/Dropdown.svelte
src/lib/forms/FloatingLabelInput.svelte
src/lib/forms/Select.svelte
src/lib/forms/Textarea.svelte
src/lib/list-group/Listgroup.svelte
src/lib/megamenu/MegaMenu.svelte
src/lib/modals/Modal.svelte
src/lib/navbar/NavDropdown.svelte
src/lib/navbar/NavHamburger.svelte
src/lib/navbar/NavUl.svelte
src/lib/navbar/Navbar.svelte
src/lib/popover/Popover.svelte
src/lib/ratings/Review.svelte
src/lib/toasts/Toast.svelte
src/lib/tooltips/Tooltip.svelte

Closes #281
This changes the `$lib` references in the components (`src/lib/*`) to relative paths, which makes this library work without having to use SvelteKit. Future components should also use relative paths in order not to break the library for non-SvelteKit users.
More details in #281 
- [✅] My pull request adheres to the code style of this project
- [❌] My code requires changes to the documentation
- [❌] I have updated the documentation as required **(not needed in this case)**
- [✅] All the tests have passed
- [✅] My pull request is based on the latest commit (not the npm version).

fix: use relative paths instead of $lib alias inside of lib

---

src/lib/utils/Popper.svelte

Correction to `on:mouseenter` handler.  
I don't know when that was changed. I can't recall doing it and I can't locate when the change was done in the history.

fix: mousenter

---

src/lib/dropdowns/DropdownItem.svelte

Closes #298 / #256
Events weren't forwarded from DropdownItem if the href attribute wasn't set.
I removed the `{#if href}` wrapped part as it seemed redundant, the only "backdraw" is that there will always be a div inside of the `<li>` tags, but I think that is alright. If not, I can revise this and just add the forwarded events directly to the li-element if no href is set

fix(DropdownItem): remove redundant part after else

---

mdsvex.config.js
package.json
pnpm-lock.yaml
src/routes/components/alert.md
src/routes/utils/ExampleWrapper.svelte
vite.config.ts

Another attempt to add `mdsvexamples` to the project.
-  no need to duplicate code and example
-  import can now be `flowbite-svelte`
-  `mdsvexample` workaround with class not needed anymore
-  `alert.md` shows the advantage of that PR

feat: mdsvexamples

---

src/lib/tabs/TabHead.svelte
src/lib/tabs/TabHeadItem.svelte
src/lib/tabs/TabWrapper.svelte
src/routes/components/tab.md

Tab component updates
* 1a6cfd32 (HEAD -> tab-update, origin/tab-update) fix: add default style to Ta
bHeadItem and TabHead and removed {tabStyle} from default example in tab page
* 5168c27c fix: remove activeTabvalue from TabWrapper and let:tabId vrom tab page examples

Tab update

---

src/hooks.server.js
tests/redirect.spec.ts

Add a server hooks to redirect /tooltip to /components/tooltip

Add server hooks to redirect component pages and add redirect test

---

src/lib/darkmode/DarkMode.svelte

See these videos, please:
https://user-images.githubusercontent.com/527641/193426844-53ca6292-998d-4304-8b59-48ee42140f78.mp4
https://user-images.githubusercontent.com/527641/193426955-4c22c110-a0b5-4d82-b015-5ae8dcf7df9e.mp4
- ✅ All the tests have passed
- ✅  My pull request is based on the latest commit (not the npm version).

fix: color flicker when changing theme using DarkMode

---

src/lib/utils/Frame.svelte

At present any component (Card, Navbar, Accordion, etc) will delay page dismount when used with Svelte-Kit due to the presence of an unused transition component within `Frame.svelte`. This causes the page to which one is transitioning to appear underneath the current page, whilst the current page is still mounted. Both are therefore displayed simultaneously, and the dismounting of the current page seems to be delayed by about 500 milliseconds.
This can already be seen in the [docs](https://flowbite-svelte.com/components/accordion). Attempting to transition from the `Card` page to the `Alert` will cause the scrollbar on the side to expand before contracting (as the next page is mounted, and subsequently the current page is dismounted). If you scroll to the bottom of the page before the …

Fix Frame components delaying page dismount in Svelte-Kit.

---

src/lib/drawer/Drawer.svelte
src/routes/components/drawer.md

- Add activateClickOutside prop to Drawer component
- Add doc Disabling outside click to drawer doc

Drawer update

---

src/lib/forms/NumberInput.svelte

Closes #344 
Missing `$$restProps` in the `NumberInput` component.

fix: restProps for NumberInput

---

src/routes/components/carousel.md

A section in Carousel component page is duplicate, so I delete it.

docs: remove duplication in Carousel page

---

src/lib/forms/Radio.svelte

This PR allows the `value` to be a `number` and not restricted to `string`

Allow value on Radio input to be a number

---

src/lib/forms/FloatingLabelInput.svelte

fix: floatinginput type changes

---

src/lib/darkmode/DarkMode.svelte
src/routes/+layout.svelte
src/routes/components/darkmode.md
src/routes/props/DarkMode.json

- make DarkMode component class configuration more friendly (users can use `class` to append classes to the default classes, so that they don't need to write the whole classes)
- users can use their desired icons in DarkMode component by `lightIcon` and `darkIcon` slots now
- rewrite the DarkMode component doc

feat: enhance DarkMode

---

src/routes/utils/MetaTag.svelte

- Twitter doesn't show og image where there are spaces
- Update MetaTag.svelte component

fix: og:image and twitter:image to replace spaces with -

---

src/routes/utils/ExampleWrapper.svelte

I really missed that feature so here we go :)
Closes #372
A copy button for code examples.
I first wanted to go with the classic copy icon but did not want to import `svelte-heros-v2` just for this one feature. But lmk if there is a desire for *style* 😆

add: Copy button to code block (ExampleWrapper)

---

src/routes/+layout.svelte

Closes #348 
Scroll to the `<main>` element (that is the direct parent element of the page content slot) after navigation.

fix: show the top of page after navigation

---

src/lib/forms/Dropzone.svelte

Closes #432
Dropzone is broken as hidden input has not have an id. 
I added an id to the hidden input and in the second commit I added a id prop as the example page shows that Dropzone gets passed an id.

fix: dropzone id and event handling

---

src/lib/navbar/NavUl.svelte

Closes #485 
Navbar slide transition - now params are exported and user can fine tune them

fix: export slide params

---

src/routes/forms/select.md

The current first example code in the <Select> component page generates raw code that is inconsistent with what is shown in Flowbite (the <select> element is contained in the <label> element).
Flowbite-Svelte:
Flowbite:

docs: fix Select example code

---

src/routes/forms/select.md

Reverts themesberg/flowbite-svelte#524
I disagree with that change. Using `<label for="...">` and embedding a form element inside the `label` is equivalent (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Label). This example was introduced like that on purpose to present both approaches.
Another point is that this PR introduce a bug, as now we have two selects with the same id, and that causes a strange focus behaviour.

Revert "docs: fix Select example code"

---

src/lib/tables/TableBodyRow.svelte
src/routes/components/table.md
src/routes/props/TableBodyRow.json

The current processing of `<TableBodyRow>`'s border stye is really weird. It changes the style of background color rather than border. And in fact, the prop `trClass` is presently used to set the styles when there are borders, and the value of this prop is also a background color style, which is also very weird. What's more, these problems cause the appearance of examples different from those displayed in Flowbite.
E.g., [Flowbite](https://flowbite.com/docs/components/tables/#default-table) (there are borders between every two `<tr>`s):
[Flowbite-Svelte](https://flowbite-svelte.com/components/table#Default_table) (the borders are missing):
BTW, I export `color` in my PR because I think there may be a situation when users want to set colors for different `<tr>` in a table.

fix: TableBodyRow color and border

---

src/routes/typography/heading.md

Fixed typo in prop `customSize`

docs: Fix typo

---

.github/workflows/playwright-and-lint.yaml
.prettierignore
package.json
playwright.config.ts
svelte.config.js

this pr runs playwright on github ci.
it could also run lint and sveltekit check, but those currently report failures.

run playwright on ci

---

src/routes/components/carousel.md

This PR fixes a small typo in the `Carousel` documentation.

docs: fix typo in carousel

---

src/lib/list-group/ListgroupItem.svelte

Closes #
ListgroupItems are forwarding two click events, one through dispatch and one through a standard forwarded event. This PR removes the dispatched click event.

Fix ListgroupItem Double Click Event

---

src/lib/timelines/Timeline.svelte
src/lib/timelines/TimelineHorizontal.svelte

Closes #606
Removes items-center class on horizontal timelines

fix: align-items class removed from horizontal timelines

---

src/lib/darkmode/DarkMode.svelte

There is a scenario when users take CSP (Content Security Policy) into consideration and `'unsafe-inline'` is usually not included in `'default-src'` and `'script-src'` for safety. For example, they configure CSP in `svelte.config.js`:
```js
const config = {
kit: {
csp: {
mode: 'auto',
directives: {
'default-src': ['self'],
'script-src': ['self'],
'style-src': ['self', 'unsafe-inline'],
}
}
}
};
```
Then an error will appear in the console because the `<DarkMode>` component directly insert the inline script in the `<head>`:
We can move the script into the `onMount` code block and frameworks like SvelteKit will automatically add a hash or a nonce onto the script.
<!--
Sync fork from GitHub dropdown and update your local branch. 
```sh
git pull origin main
git …
```

Fix theme inline script

---

src/hooks.server.js
src/routes/+page.svelte
src/routes/landing/GetStarted.svelte
src/routes/utils/CopyCliboardInput.svelte

Get started - bottom element at the Home Page

feat: GetStarted element

---

src/routes/utils/CopyCliboardInput.svelte
src/routes/utils/Footer.svelte
src/routes/utils/Newsletter.svelte

Closes https://github.com/themesberg/flowbite-svelte/issues/698
This PR improves text wrapping and spacings on mobile devices.
Before:
After:

docs(footer): fix wrapping and spacings on mobile devices

---

src/routes/utils/index.ts
src/routes/utils/mdsvex.d.ts

Typescript declaration for the import of markdown files in `index.ts` file.

fix: typescript declarations for import.meta.glob

---

src/lib/forms/Input.svelte
src/routes/props/Input.json

Closes #727 
Update the `Input` component's `value` type to be `any` which aligns with svelte/elements [HTMLInputAttributes](https://github.com/sveltejs/svelte/blob/master/elements/index.d.ts#L757)

fix: input component value type to any

---

src/lib/accordion/Accordion.svelte

Closes #768 
Since all the Accordion props have default values them should be optional in type descryptor.

accordion optional props

---

src/lib/darkmode/DarkMode.svelte

Closes #
- patch to fix dark mode. When a browser is refreshed, now it set the theme in localStorage
- this won't fix flush problem

feat: darkmode fix for refreshing a browser

---

src/lib/ratings/Star.svelte
src/routes/props/Star.json

Closes #
Fixes issue when trying to use multiple Star components with different fill colors, for example:
```
<Star fillColor="blue"/>
<Star fillColor="orange"/>
```
Since the internal ids were the same, they both were coming out blue.
This update will generate unique ids, following the same pattern as Rating.

fix: generate a unique id for each star so fill can be different

---

src/lib/buttons/Button.svelte
src/lib/buttons/GradientButton.svelte
src/routes/docs/components/button.md

I noticed that the Button components do not forward the touchevents. However, these are essential for mobile development. So I added them to the list of forwarded events.

Added touchevent forwarding to Buttons

---

src/lib/drawer/Drawer.svelte

Fix to `Drawer` transitions.
With the move to Svelte 4 transitions became local by default. Drawer had a nested `if`s structure so local transitions stopped to work.

fix: transitions in drawer

---

src/lib/utils/Frame.svelte

Same fix as for the drawer. Local transitions were blocked by nested `if`.

fix: transitions in frame

---

src/lib/forms/Toggle.svelte

Currently on small device sizes the toggle shrinks and clips. This PR resolves this by adding `shrink-0`.
https://github.com/themesberg/flowbite-svelte/assets/8170676/deb3c691-cbe9-4447-9f8a-c50e7107b1cd
https://github.com/themesberg/flowbite-svelte/assets/8170676/84269753-b0c0-4ca1-b279-41ec601222ce

fix: add shrink-0 to prevent toggle UI from shrinking on small screen sizes

---

src/lib/paginations/Pagination.svelte
src/lib/paginations/PaginationItem.svelte
src/routes/docs/components/pagination.md

Closes #894 
Update to pagination component.

feat: pagination large

---

src/routes/+layout.svelte

Workaround for scrolling to the anchor when copy/pasting url in the navigation bar of the browser.
Source: https://github.com/sveltejs/kit/issues/2664

fix: workaround for scroll to anchor

---

src/lib/forms/Input.svelte

Adjust the way the type attribute is set to use a reactively spread object rather than a custom action to circumvent the svelte warning. The motivation for this change is that currently the border is dependent on a `type` attribute being set on the input, which gets its styling from the global Flowbite CSS file. 
This causes a brief flicker in the input's border given the attribute is being set with javascript after it first mounts, and just doesn't render a border at all if JS is disabled.
With the reactive spread, the input does have the type attribute already set on mount so the border will be present even without JS.
Also not sure if the border class should just be added in the defaultClass as well, but this is a less breaking change.

fix(Input): Use a reactive spread instead of custom action to set Input `type` attribute

---

src/lib/forms/FloatingLabelInput.svelte

Use a reactive spread for floating label input type attribute, consistent with change from #921

fix(FloatingLabelInput): Use reactive spread for type attribute

---

pnpm-lock.yaml
src/lib/accordion/AccordionItem.svelte

This change involves duplicating conditionally shown content shown inside the `{#if open}` block to still render in the DOM but hidden with CSS. This closer aligns to the implementations of the components for the [core Flowbite library](https://flowbite.com/docs/components/accordion/) and the [Flowbite React library](https://www.flowbite-react.com/docs/components/accordion), and has an added benefit of allowing the relevant content inside an accordion to be crawled by search engines.

fix/feat: Keep AccordionItem content hidden in DOM even when closed

---

src/lib/bottom-nav/BottomNavHeaderItem.svelte

Closes #938 
Added missing event handler to `BottomNavHeaderItem`

fix: Added events to `BottomNavHeaderItem`

---

src/lib/dropdowns/Dropdown.svelte
src/routes/docs/components/dropdown.md
src/routes/props/Dropdown.json

Closes #939 
Closes #897
Added `z-50` to the dropdown container so it always stays on-top of all elements (e.g. no longer hidden behind a `ListGroupitem`.

fix: Added z-50 to dropdown container so it always stays on top

---

src/lib/modals/Modal.svelte
src/routes/docs/components/modal.md

Allows user overwriting the default Modal body class through the bodyClass prop.
Closes #

feat: allow customization of body class in Modal component

---

src/lib/forms/MultiSelect.svelte

Closes #952 
Added `type="button"` to the button surrounding the chevron.

fix: #952 multiselect

---

src/lib/speed-dial/SpeedDial.svelte
src/routes/docs/components/speed-dial.md

Exporting `open` in `SpeedDial` so you can control the popup status,
As requested on Discord - now you can close popup once clicked on any element. See example:
```svelte
<script>
import { SpeedDial, SpeedDialButton } from 'flowbite-svelte';
let open = false;
const close = () => {open =  false};
</script>
<SpeedDial bind:open>
<SpeedDialButton name="Share" on:click={close}>Share</SpeedDialButton>
<SpeedDialButton name="Print" on:click={close}>Print</SpeedDialButton>
</SpeedDial>
```

feat: export open in speeddial

---

src/routes/docs/components/popover.md
src/routes/docs/components/tooltip.md

Border color on `External reference` examples for `Tooltip` and `Popover`.

fix: border color on popup examples

---

src/lib/forms/Search.svelte

Removes padding from the slot container on the search input as it breaks button positioning.
- [x ] My pull request adheres to the code style of this project

fix: Search component - remove padding from default slot container

---

src/lib/index.ts

I tried to extend a component by copying its contents into my own file, but I ran into issues accessing the `Frame` component:
```
import Frame from 'flowbite-svelte/dist/utils/Frame.svelte';
```
results in:
```
Missing "./dist/utils/Frame.svelte" specifier in "flowbite-svelte" package
```
And:
```
import { Frame } from 'flowbite-svelte';
```
results in:
```
Module "flowbite-svelte" has no exported member 'Frame'.
```
This PR resolves the issue by adding the `Frame` component to the exports in `src/lib/index.ts`

Add Frame component to exports

---

src/lib/badges/Badge.svelte

The documented example for close events on a dismissable `Badge` is currently not working. The code from the docs is:
```js
<script>
import { Badge } from 'flowbite-svelte';
function handleClose(event) {
alert('Badge dismissed');
}
</script>
<Badge dismissable large on:close={handleClose}>Default</Badge>
```
Furthermore, the close event still needs to be added to the documentation.

Fix missing dispatch of close events for badges

---

src/lib/carousels/Carousel.svelte

This PR fixes the custom Carousel styling which was lost when adding swiper component by re-adding custom `imgCls` and `slideCls`.
This PR also inverts the order of the carousel swiper direction to match expected behavior from other swiping libraries such as SwiperJS (swipe from left->right to go back, right->left to go forward).
See: https://github.com/themesberg/flowbite-svelte/pull/965

Bugfix: Carousel Swiper Styling & Direction

---

src/lib/datepicker/Datepicker.svelte

The `Datepicker` component has a `attributes` prop that can be used to set toggle-type attributes, causing issues when the attribute is an empty string (which it is by default).  This fixes #985 by adding a check to filter out empty attributes.
Closes #

fix: ignore empty attributes in Datepicker

---

src/lib/types.ts

Makes the exported `ButtonColorType` match the type for the `Button` component's `ButtonColor` type.
When creating a custom `Button` type to set a default color as per the recommendation [in the docs](https://flowbite-svelte.com/docs/pages/customization#Global_customization), using the `ButtonColorType` exported by `flowbite-svelte/dist/types` generates a type error. `ButtonColorType` does not match the colors defined by the `ButtonColor` type on the `Button` component. This PR syncs them up.

Match ButtonColorType to Button component ButtonColor

---

src/lib/carousels/Carousel.svelte
src/lib/carousels/Slide.svelte

Closes #1050
Fixes the strange behaviour of images on iPad's.
Needed to remove: `style={`transform: translateX(${percentOffset}%)`}` from the wrapping `div`.
This need a further verifying why it was needed. Probably some touch / slide management.

fix: display on iPads

---

src/lib/drawer/Drawer.svelte

Closes #1080
This PR introduces a check in the Drawer component which allows changing the value of `activateClickOutside` after the component is mounted.
This is done by adding `activateClickOutside` as a condition inside the function called by `clickOutsideWrapper`.
This fix assumes that the behaviour is not intentional.

fix: check activateClickOutside on outside click

---

src/lib/carousel/Carousel.svelte
src/lib/carousel/Carousel.ts
src/lib/carousel/Controls.svelte
src/lib/carousel/Slide.svelte
src/lib/carousel/Thumbnails.svelte
src/routes/docs/components/carousel.md

- Feature: Re-exposes the ability for custom image styling which was removed during the recent Carousel API update. This change now allows for tailwind classes to be passed to the `img` element inside the `Slide` component
- Bugfix: Looks like #1045 added a bug for swiping on mobile devices: `Unable to preventDefault inside passive event listener invocation`. This is an example of the error on the current Flowbite Svelte webpage:
https://github.com/themesberg/flowbite-svelte/assets/4033621/faef943b-6297-4c8a-9907-9a1fc04186cf
- Bugfix: Also, this PR fixes issues with Touch events, such as onDragStop not firing in certain environments. Touch event listeners need to also be added on the Carousel `div` element to work properly without throwing errors across different environments.
- [] Not …

Bugfix: Carousel swiping event listener error, Feat: Re-Expose Image Class styling for Carousel

---

src/lib/modal/Modal.svelte

Adds missing properties on the Modal component. This allows the use of these options when using typescript.
The naming of `bodyClass` doesn't match the other patterns of class naming parameters. It may be good in the future to adjust this functionality and introduce a `classBody` parameter as well, so that it functions the same as other class modifiers.

fix: add missing types on Modal $$Props

---

src/routes/docs/typography/list.md

Updated docs ordered list example to actually use `tag="ol"`

Updated ordered list example to actually use `tag="ol"`

---

src/lib/modal/Modal.svelte
src/routes/docs/components/modal.md

`Modal`
- division lines between header, body and footer changed from `border-t` / `border-b` to `division-y` on parent
- you can now change the color of those by adding `class='division-color-value'` to `Modal`
- or remove those completely by  `class='division-y-0'` 
Minor formatting to docs made as well.

fix: modal divide-y instead of border

---

src/lib/forms/Textarea.svelte

This PR fixes a visual issue with `Textarea` having a header or footer. If  `Textarea` has a header and no footer, the bottom corners of `Textarea` will appear to be missing. The same applies if there is only a footer.
| with header (current ver.) | 
| :--: | 
| ![image](https://github.com/themesberg/flowbite-svelte/assets/40572953/aa71737e-f3b5-473e-90b8-bba5bcf245fd) | 
The bottom corners are missing
| with footer (current ver.) |
| :--: |
| ![image](https://github.com/themesberg/flowbite-svelte/assets/40572953/3bb271f0-66af-4344-9e89-44c23b900f9c) |
The top corners are missing
| fixed |
| :--: |
| ![image](https://github.com/themesberg/flowbite-svelte/assets/40572953/197fcdda-d881-47b4-8b35-90ce1b14c7d2) |
| ![image](https://github.com/themesberg/flowbite-svelte/assets/40572953/ad77fe46 …

fix: textarea inner rounded

---

src/lib/modal/Modal.svelte

Modal closes on mouse up (when a click outside modal is released)
Listen to mousedown instead click and handle outsideclose

fix: modal outside click only on mouse down

---

src/lib/utils/Popper.svelte
src/routes/docs/components/dropdown.md

Closes #1158
Removal of the custom event dispatcher made the dropdown examples to stop working. Fix provided here.
Added as well a link to Floating UI to explain `Placement` values.

fix to dropdown docs

---

src/lib/forms/Radio.svelte

Closes #1219
The radio form component has a prop called group. This is a svelte-specific prop that lets you bind to the value of the selected radio element. The prop is currently exported default as an empty string. The group being an empty string for all radio elements causes some weird overrides of the expected behavior like shown in #1219.
My solution is to simply set the default to undefined instead of an empty string because then it works with svelte as expected. I tried null and that caused some bugs too so undefined seems like the only correct value.
The npm tests won't run on my computer and I can't figure out why. It is probably something simple though as I don't have any experience with playwright.

Radio group prop bug fix.

---

src/lib/dropdown/Dropdown.svelte

Few things in `Dropdown`:
- `classContainer`, `classHeader` and so on currently are not declared with `let` and instead accessed through `$$restProps`. Because of that theirs usage is untyped (Svelte will show an error with "Object literal may only specify known properties") and does not remove those props from `$$restProps` which causes them to be passed down and create html attributes like `classcontainer`.
- In `$$Props` `activeClass` was not declared and `open` was but not needed (it is already propagated from `Popper`).
- Merged classes weren't reactive so consequent changes to any class props (including `class`) were ignored.

fix: properly handle class props in dropdown

---

src/lib/speed-dial/SpeedDial.svelte
src/lib/utils/Popper.svelte
src/routes/docs/components/popover.md

Right now `Popper` has two trigger modes - "click" and "hover". Both of them react to focus too but do hide content on consequent `click`s or `mouseleave`s even if a trigger element is still focused.
This is a small change that adds third mode called "focus" that ignores mouse events and shows/hides solely based on focus status.
For me it is mainly about inputs. There is "Password strength" section on Popper documentation page. And right now you can see password strength feedback only if your mouse is over the input there. But I prefer to continue giving feedback on user typing a password even if they moved mouse away. And in my particular case I wanted to make `Input` + `Dropdown` work for autocomplete of sorts but both "click" and "hover" are not really suitable for that.

feat: add focus only trigger mode for Popper

---

src/lib/modal/Modal.svelte

Currently header in Modal uses `p-4` but body and footer use `p-6` making them unaligned. While code in [Flowbite docs](https://flowbite.com/docs/components/modal/) consistently uses `p-4 md:p-5`.
Corrected that and two related things: `space-y-6` to `space-y-4` for body and `space-x-2` to `space-x-3` for footer.

fix: correct padding in Modal

---

src/lib/forms/Textarea.svelte
src/lib/toolbar/ToolbarButton.svelte

There are 7 places where `getContext('background')` is used - `Checkbox`, `Input`, `InputAddon`, `Radio`, `Textarea`, `Toggle` and `ToolbarButton`. In all of them except `Textarea` this context only slightly changes color of some aspect in dark mode. But in `Textarea` it also changes `bg-gray-50` to `bg-white`.
Removed that switch to be consistent with other components. (And in `ToolbarButton` just moved the same class from a conditional statement.)

fix: background context should affect only dark background in Textarea

---

src/lib/forms/Checkbox.svelte
src/lib/forms/Radio.svelte
src/routes/docs/forms/checkbox.md

Spacing for `Radio` and `Checkbox` is valid only when the ones are wrapped with `Label`.

radio/checkbox: spacing only when label is on

---

src/lib/forms/MultiSelect.svelte

Closes #
Currently the `Multiselect` always opens, no matter where you click inside of it. So if the user has an item selected (and added as a `Badge` inside the input), and they click on it, the dropdown opens, but without focus. 
This results in a not-closable dropdown on outside clicks

fix: don't open multiselect dropdown on clicking selected items
