themesberg/flowbite-svelte

- src/lib/navbar/NavLi.svelte
i have been using this like 
```
<NavUl {hidden}>
<NavLi href="/" active={$page.url.pathname === '/'}>Home</NavLi>
<NavLi href="/about" active={$page.url.pathname === '/about'}>About</NavLi>
</NavUl>
```
this would only update on the first time the route changes and break afterwrads, with this change it works all the time
> made aClass reactive based on active

- src/lib/forms/SimpleSearch.svelte
- src/lib/index.ts
- src/routes/forms/search.md
- src/routes/props/SimpleSearch.json
Closes # 
add simple search and doc and check the version
> RE: feat: add simple search 

- src/lib/buttons/Button.svelte
Closes #97
Make disabled button unclickable
**Before**
**After**
> fix: make disabled button unclickable

- src/lib/buttons/Button.svelte
Closes #99 
Make button styles reactive
> feat: make button styles reactive

- src/routes/breadcrumbs/index.md
Fix breadcrumb import from
From
```svelte
import { Breadcrumb } from '$lib/index'
```
To
```svelte
import { Breadcrumb } from 'flowbite-svelte'
```
> docs: fix breadcrumb import from

- src/lib/darkmode/DarkMode.svelte
Simplified implementation. Uses dynamic variable instead of querying document for elements.
> DarkMode - simplified implementation.

- src/lib/alerts/Alert.svelte
> Alerts - too many if's

- src/lib/toasts/Toast.svelte
- src/lib/utils/CloseButton.svelte
- src/routes/toasts/index.md
Toasts module re-implemented. Some API simplification and place for extensions added.
I've added a new component `CloseButton.svelte` as that can be re-used in other modules like Alerts.
I've put it under `$lib/utils/` but it can be moved to other location if needed.
> Toasts re-factored. API simplified.

- src/routes/Toc.svelte
- src/routes/__layout.svelte
Simple Toc component, floating to the right top, with the layout copied from Flowbite.com
> feature: floating toc for documentation pages

- src/lib/alerts/Alert.svelte
- src/routes/alerts/index.md
- src/routes/props/Alert.json
Alerts module. Simplification of the API and extensions to documentation.
> featrue: alerts changes and extentions

- src/lib/avatar/Avatar.svelte
- src/lib/avatar/Dot.svelte
- src/lib/avatar/Placeholder.svelte
- src/lib/types.ts
- src/routes/avatar/index.md
- src/routes/props/Avatar.json
- tailwind.config.cjs
Alerts - re-structured code, cleaned up API, added missing variants.
Implementation of  #5. Now missing only the dropdown.
> feat: alerts more functions, changed API

- src/lib/buttons/Button.svelte
- src/routes/buttons/index.md
Fix to buttons:
- sizes - buttons padding was somehow not in line with Flowbite.com, now updated
- icon only buttons - changes in doc to show how to force round/square layout
> fix: buttons - update sizes and force round

- src/routes/icons/index.md
Closes # 
replaced the [broken link](https://github.com/shinokada/svelte-heros/blob/main/icon-names.md) to the icon names list in [svelte-heros](https://github.com/shinokada/svelte-heros) repo with the [working link](https://github.com/shinokada/svelte-heros/blob/main/icon-list.md)
If your branch is behind the upstream master, I will have difficulties to merge the request. Please fetch the latest version of the branch:
```sh
```
or
```sh
```
> Fixed outdated link to svelte-heros icons list

- src/routes/dropdowns/index.md
Update to dropdowns:
- fixed detached mulit-dropdown at small displays
- added radio and toggle examples
> fix: multi-dropdown detach

- src/lib/forms/Toggle.svelte
> fix: #165 toggle bind:group bind:checked

- src/lib/dropdowns/Dropdown.svelte
Move the ChevronLeft to the left side of the button.
> fix: dropdown ChevronLeft position

- src/lib/forms/Label.svelte
- src/lib/forms/Select.svelte
- src/routes/forms/select.md
Implementation of #50 
- Select input example
- Disabled state
- Underline select
- Select with dropdown
- Sizes
TODO: Select with `multiple` prop and wrapped in component causes issues in Svelte. This is similar to the checkbox' `bind:group` issue. Option `multiple` is not implemented though.
> feat: select input #50

- src/routes/pages/getting-started.md
Fixed small typo in `Getting Started` page of the documentation.
> Fixed small typo

- src/lib/badges/Badge.svelte
- src/lib/forms/Input.svelte
- src/lib/forms/Toggle.svelte
- src/lib/list-group/List.svelte
- src/lib/list-group/ListItem.svelte
- src/lib/megamenu/MegaMenu.svelte
- src/lib/utils/CloseButton.svelte
- src/lib/utils/OptsButton.svelte
Few fixes here and there:
- not used code in MegaMenu
- relative class change in Toggle
- default value for href in Badge
- tinted color support for Input
- background color for List and ListItem
- added OptsButton - like CloseButton but with 3 horizontal dots.
> fix: various minor fixes

- src/lib/buttons/Button.svelte
- src/routes/cards/index.md
Fixed:
- /cards/index.md - `link` replaced to `href`
- Button.svelte clean up of code
> fix: cards/index.md, buttons

- src/lib/alerts/Alert.svelte
- src/lib/forms/Checkbox.svelte
- src/lib/forms/Toggle.svelte
- src/routes/alerts/index.md
- src/routes/forms/radio.md
- src/routes/modals/index.md
- `on:change` added to `Checkbox` and `Toggle`
- text color tweak for `Alert`
- some formatting of docs
> fix: minor fixes / fine tuning

- src/lib/badges/Badge.svelte
- src/lib/utils/CloseButton.svelte
- src/routes/badges/index.md
- src/routes/mega-menu/index.md
New features of `Badge`
- notification badge
- button with badge
- dismissable badge
> feat: badges new features

- src/lib/avatar/Avatar.svelte
- src/lib/avatar/Placeholder.svelte
- src/routes/avatar/index.md
Avatar - few tweaks and additional examples
> feat: avatar w/tooltip / initials

- src/routes/__layout.svelte
- src/routes/footer/index.md
Fixing a small typo in the docs 😄
If your branch is behind the upstream master, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
```sh
```
or
```sh
```
> chore: fixed github typo in docs

- src/routes/cards/index.md
Cards doc page. 
References of CardsSignIn and CardsEcommerce replaced by embedded examples.
`
> chore: cards documentation

- src/lib/tooltips/Tooltip.svelte
Fix to #200 
- Arrow position calculation for tooltip fix.
- Some parameter passing simplification
> fix: #200 undefined in tooltips

- src/routes/alerts/index.md
Removal the non standard color for 'Alert with list', after correction at Flowbite.com
> fix: alerts with list color removal

- src/lib/cards/Card.svelte
- src/routes/cards/index.md
Extra examples:
- Card with link
- Pricing card
- Testimonials card
I have not done Tabs examples yet as I'm not happy with Tabs component implementation. I need to work on the Tabs before.
> chore: extra card examples

- src/lib/modals/Modal.svelte
- src/routes/modals/index.md
Crypto wallet in Modal
Closes Modal #176
> feat: modal - crypto

- src/app.css
- src/app.html
Fonts as in Flowbite.com
This applies to the docs application, to be in `Flowbite.com` look and feel.
> chore: google fonts as in Flowbite.com

- src/routes/forms/checkbox/+page.md
- src/routes/forms/radio/+page.md
- src/routes/popover/+page.md
- docs update for `Radio` - closes #232 
- placement example for `Popover`
If your branch is behind the upstream master, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
```sh
```
or
```sh
```
> fix: docs for radio

- src/lib/buttons/Button.svelte
Correction to diveder line in `ButtonGroup`
> fix: buttongroup divider

- src/lib/avatar/Avatar.svelte
- src/lib/avatar/Dot.svelte
Fix for `Avatar` status dot positioning.
> fix: avatar dot alignment

- src/routes/forms/textarea/+page.md
`Textarea` docs updated with the example using `Toolbar` component.
> fix: textarea docs

- src/routes/cards/+page.md
- src/routes/dropdowns/+page.md
- src/routes/forms/checkbox/+page.md
- src/routes/forms/select/+page.md
Fixes due to `Dropdown` API changes
> fix: docs fixes due to dropdown api change

- src/routes/dropdowns/+page.md
Quick fix to `Dropdown` examples.
If your branch is behind the upstream master, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
```sh
```
or
```sh
```
> fix: no dropdown docs

- src/lib/dropdowns/Dropdown.svelte
- src/lib/dropdowns/DropdownItem.svelte
- src/lib/index.ts
- src/lib/megamenu/MegaMenu.svelte
- src/lib/navbar/NavHamburger.svelte
- src/lib/navbar/NavLi.svelte
- src/lib/navbar/NavUl.svelte
- src/lib/navbar/Navbar.svelte
- src/lib/toolbar/ToolbarButton.svelte
- src/lib/utils/Chevron.svelte
- src/lib/utils/Frame.svelte
- src/lib/utils/Popper.svelte
- src/routes/mega-menu/+page.md
- src/routes/navbar/+page.md
Navbars in Flowbite.com have changed. Especially in mobile view.
This PR
- tries to bring the compatibility with above changes
- uses `Frame` to implement navbar components
- adds few examples to navbar docs
- some other non-navbar tweaks 
- `Dropdown` color and border fine tune
- `DropdownItem` to be `<a>` and remove of `tabindex`
> fix: navbar updates

- src/lib/forms/Range.svelte
- src/routes/forms/range/+page.md
`$$restProps` used for `Range.svelte`
> feat: range - clean up

- CHANGELOG.md
- mdsvex.config.js
- package.json
- pnpm-lock.yaml
- src/routes/components/alert.md
- src/routes/pages/getting-started.md
- src/routes/utils/ExampleWrapper.svelte
- vite.config.js
`mdsvexample` - another try to make a PR
- no need to duplicate code and example
- import can now be `flowbite-svelte`
- `mdsvexample` workaround with `class` not needed anymore
- `alert.md` shows the advantage of that PR
If your branch is behind the upstream main, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
> feat: mdsvexample second try

- src/routes/pages/getting-started.md
Added a new section in the Getting started page.
List of starter kits.
If your branch is behind the upstream main, I may have difficulties to merge the request. Please fetch the latest version of the main branch:
> docs: add starters to Getting startedpage

- src/lib/popover/Popover.svelte
- src/lib/tooltips/Tooltip.svelte
- src/lib/utils/Popper.svelte
Fix for #287 
Needed to add various classes and data parameters so that `flowbite.css` recognizes properly `tooltips` and `popovers`.
> fix: tooltips/popovers

- src/lib/sidebars/SidebarDropdownWrapper.svelte
- src/routes/components/sidebar.md
Closes #302
- Add a feature to change up/down icon when you open/close sidebar dropdown.
- User can add own icon using `arrrowup` and `arrowdown` slots.
> Sidebar arrow update

- src/lib/utils/Frame.svelte
> Fixed typo

- .github/pull_request_template.md
- .github/workflows/release-please.yml
- README.md
- src/routes/blocks/FileinputBlock/+page.svelte
Closes #307 
Update README table by adding new components.
> docs: add components to README table

- src/lib/tooltips/Tooltip.svelte
- src/routes/components/tooltip.md
- src/routes/props/Tooltip.json
> Tooltips update

- src/lib/tabs/TabContentWrapper.svelte
- src/lib/tabs/TabHead.svelte
- src/lib/tabs/TabHeadItem.svelte
- src/lib/tabs/TabWrapper.svelte
- src/routes/components/tab.md
Tab components update:
- e94b3449 fix: update icon class in TabHeadItem for Tabs with icons
- 5f46d238 fix: remove tabId from TabWrapper component
- 2d7131b2 fix: add classOptions type to classes object
> Tab update

- src/lib/forms/Iconinput.svelte
- src/lib/forms/Input.svelte
- src/routes/forms/input-field.md
Closes #312 #316 
Add forward events to IconInput and on:input to Input components.
> fix: add events to IconInput and on:input to Input components

- src/app.css
- src/lib/tooltips/Tooltip.svelte
Update in usage of the `color` property.
> fix: correction in using style and color

- src/lib/toasts/Toast.svelte
- src/routes/components/toast.md
`Toast` to use more standard naming:
- `visible` changed to `open`
- `postition` changed from `tr|tl|br|bl` to `top-left|top-right|bottom-left|bottom-right`
> feat: toast fine tune

- src/lib/buttongroups/ButtonGroup.svelte
- src/lib/forms/Input.svelte
- src/lib/forms/InputAddon.svelte
- src/lib/forms/Search.svelte
- src/lib/types.ts
- type `Size` renamed to `SizeType`: `xs | sm | md | lg | xl`
- type `FormSizeType` created: only `sm | md | lg`
- removal of unused types: `AvatarType`, `ButtonGroupType`, `CardButtonType`
> types cleanup

- src/lib/accordions/Accordion.svelte
- src/lib/accordions/AccordionItem.svelte
- src/lib/types.ts
- src/routes/components/accordion.md
Quick fixes to `Accordion`:
- common `AccordionCtxType`
- `slot name=body` changed to default slot
- update in doc and examples
> fix: accordion slots + docs

- src/lib/forms/Input.svelte
Fixed icon regression on `Input`.
> fix: input icons

- src/lib/utils/focusTrap.js
I found a better implementation of the focus trap used by `Modal`. It's safer against unwanted scenarios of focus away from the modal dialog.
Change is transparent for any other code.
> fix: improved focustrap

- src/lib/carousels/CarouselTransition.svelte
Small easy fix. Carousel was starting at index 1 instead of the first slide - I'd image this was unintended.
- [ x] My pull request adheres to the code style of this project
- [ x] My code requires changes to the documentation
- [ x] I have updated the documentation as required
- [ x] All the tests have passed
- [ x] My pull request is based on the latest commit (not the npm version).
> Start CarouselTransition index at 0

- src/lib/forms/Input.svelte
- src/lib/forms/NumberInput.svelte
- src/lib/index.ts
- src/routes/forms/input-field.md
Proposal of the workaround for dynamic `input` type.
> fix: input number workaround

- src/lib/cards/Card.svelte
- src/lib/list-group/ListgroupItem.svelte
- src/lib/ratings/Rating.svelte
- src/routes/components/card.md
Fix for #357 
- x-padding adjustments for `Card.svelte`
- x-padding adjustment for `ListgroupItem`
> fix: card padding-x in mobile view

- src/lib/cards/Card.svelte
- src/routes/components/card.md
Closes #206 
Add missing `$$restProps` to underlying `Frame` in the `Card` component.
> fix: card - restProps

- src/routes/+layout.svelte
Add dropdowns to the sidebar menu.
> docs: add dropdown to sidebar menu

- src/routes/forms/input-field.md
Closes #48
Missing dropdown example for `Input` component
> fix: missing dropdown example

- src/lib/drawer/Drawer.svelte
- src/routes/components/drawer.md
Closes #389
- Add if-else for Drawer 
- Add examples on doc
> feat: add disabling only outside click but not backdrop

- src/routes/components/table.md
Closes #
correct typo: 'stiped' => 'striped'
- [X ] I have updated the documentation as required
- [ X] My pull request is based on the latest commit (not the npm version).
> Update table.md to correct typo: 'stiped' => 'striped'

- src/lib/list-group/Listgroup.svelte
- src/lib/modals/Modal.svelte
- src/lib/navbar/NavUl.svelte
- src/lib/navbar/Navbar.svelte
- src/lib/toasts/Toast.svelte
Add `{...$$restProps}` to Modal/Frame
> Add color to modal frame and type fixes

- src/lib/modals/Modal.svelte
- src/routes/components/modal.md
Adds `color` support to `Modal`.
Address partially #404
> Modal - color support

- src/lib/forms/Search.svelte
Missing `on:input` event forwarder for `Search` component.
> fix: search on:input

- src/routes/+layout.svelte
This PR fixes a typo in the sidebar for the docs
> fix typo ("typtography" -> "typography")

- src/app.d.ts
- src/lib/modals/Modal.svelte
- src/routes/components/modal.md
Closes #413
Setting the `autoclose` to `false` by default for `Modal` component.
> fix: autoclose=false (default)

- src/routes/forms/radio.md
Closes #424 
Correction in 'radio.md' docs
> fix: radio.md - dropdown

- src/lib/forms/Checkbox.svelte
- src/routes/forms/checkbox.md
Correction to group variable management in `Checkbox`.
On changing checkbox value the group was correctly modified, but on change of the group variable checkboxes were not updated. Now it's fixed.
> Checkbox group

- src/lib/forms/Checkbox.svelte
- src/routes/forms/checkbox.md
Closes #430 
Fix to apply the `checked` attribute value when initializing the `Checkbox`.
> fix: checkbox initial checked

- src/lib/forms/Checkbox.svelte
- src/lib/forms/Toggle.svelte
- src/routes/utils/ExampleWrapper.svelte
Closes #438
Second try to close #438
+ one change in `ExampleWrapper` to clear out the warnings about `src` prop.
> fix: toggle initial checked

- src/app.html
Closes #440 #421 #381
Thanks to the Chrome team the issue is found and solution proposed:
https://bugs.chromium.org/p/chromium/issues/detail?id=1392467
This PR adds the class `relative` to `#svelte` element.
> fix: double scrollbar in docs

- src/lib/tables/TableBodyCell.svelte
- src/lib/tables/TableBodyRow.svelte
- src/lib/tables/TableHead.svelte
Closes #387
Closes #443 
Add `on:click` to `TableBodyRow` and `TableBodyCell`
> feat: make tr and td clickable

- src/lib/avatar/Avatar.svelte
Closes #460 
Fix to avatar default `href`. Is `undefined` now instead of `#`.
> fix: avatar default href

- src/lib/tooltips/Tooltip.svelte
- src/lib/utils/Popper.svelte
Fine tune to tooltip/popper:
- removal of the border from popper - was causing misalignment of the tooltip-arrow
- dark tooltip has no border in Flowbite.com - aligned
- tooltip style default to 'dark'
> remove border

- src/lib/buttons/Button.svelte
Fix to buttons:
- `focus:outline-none` was not applied on normal buttons
> button outline

- src/lib/utils/Popper.svelte
Closes #402 
Optional handler function should return nullish value not boolean.
> fix: ts errors

- src/routes/typography/link.md
file was moved from buttongroups to typography
Closes #
> fix A example link

- src/lib/typography/A.svelte
Closes #
This PR is to allow links to receive click events.
> allows link click event

- src/lib/list-group/ListgroupItem.svelte
Closes #466 
Fix: correction to padding in `ListGroupItem` when if mobile view.
> fix: list group item padding

- src/lib/forms/Range.svelte
- src/lib/forms/Textarea.svelte
- src/lib/megamenu/MegaMenu.svelte
- src/lib/navbar/NavDropdown.svelte
- src/lib/toasts/Toast.svelte
- src/lib/toolbar/Toolbar.svelte
- src/lib/toolbar/ToolbarButton.svelte
- src/lib/types.ts
- src/lib/utils/backdrop.ts
- src/routes/+error.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/datepicker/+page.svelte
- src/routes/layouts/testLayout/+page.svelte
Some fixes for `npm run check`
> fix: npm run check fixes

- package.json
- pnpm-lock.yaml
- src/lib/forms/Range.svelte
- src/lib/forms/Textarea.svelte
- src/lib/megamenu/MegaMenu.svelte
- src/lib/navbar/NavDropdown.svelte
- src/lib/toasts/Toast.svelte
- src/lib/toolbar/Toolbar.svelte
- src/lib/toolbar/ToolbarButton.svelte
- src/lib/types.ts
- src/lib/utils/backdrop.ts
- src/routes/+error.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/datepicker/+page.svelte
- src/routes/layouts/testLayout/+page.svelte
Update dependency SvelteKit to 1.0.1.
> Sveltekit 1 update

- src/lib/paginations/Pagination.svelte
- src/lib/paginations/PaginationItem.svelte
- src/lib/types.ts
- src/routes/components/pagination.md
Closes #496 
- Add active prop 
- Add examples to the pagination page
> feat: add pagination examples

- src/lib/paginations/Pagination.svelte
- src/lib/paginations/PaginationItem.svelte
> fix: pagination for darkmode

- src/lib/forms/Input.svelte
Closes #510 
Added missing placeholder colors for dark mode to validation states.
> fix:color for input validation

- src/lib/forms/Input.svelte
Closes #510 
Added dark text color for input validation.
> fix: dark text color for input validation

- src/hooks.server.js
- src/lib/accordions/AccordionItem.svelte
- src/lib/badges/Badge.svelte
- src/lib/footer/FooterLink.svelte
- src/lib/forms/Toggle.svelte
- src/lib/paginations/PaginationItem.svelte
- src/lib/ratings/Rating.svelte
- src/lib/ratings/RatingComment.svelte
- src/lib/types.ts
- src/lib/utils/backdrop.ts
- src/routes/+error.svelte
- src/routes/+layout.js
- src/routes/components/[slug]/+page.js
- src/routes/extend/[slug]/+page.js
- src/routes/forms/[slug]/+page.js
- src/routes/pages/[slug]/+page.js
- src/routes/typography/[slug]/+page.js
- src/routes/utilities/[slug]/+page.js
Few fixes to errors printed by `npm run check`. The work towards closing #484
> fix: npm run check corrections

- src/routes/components/table.md
Add missing backquote wrapper for the `<tfoot>` element
Before this PR:
- ![image](https://user-images.githubusercontent.com/25318236/212012056-bef2ef76-f453-4c05-9432-eddb46a359d5.png)
- ![image](https://user-images.githubusercontent.com/25318236/212011854-8a447195-4c25-4cbb-81d8-4a4e0f8afd72.png)
- ![image](https://user-images.githubusercontent.com/25318236/212011939-0fd4a33c-f2e9-4142-b6b3-32d626de9330.png)
> chore: add missing element wrapper

- src/lib/modals/Modal.svelte
- src/routes/components/modal.md
This PR touches the problem raised in PR #519, but introduces more changes.
- backdrop is now separated from the main dialog
- backdrop is full screen, while dialog is positioned with `h-modal` for small screens (in accordance with Flobite.com)
This should address #523 as well.
> fix: modal layout

- src/lib/indicators/Indicator.svelte
- src/routes/components/indicators.md
`Indicator` - few minor tweaks.
> fix: few minor tweaks

- src/lib/index.ts
- src/lib/steps/StepIndicator.svelte
- src/routes/components/step-indicator.md
- src/routes/props/StepIndicator.json
- tests/components.spec.ts
Added a step indicator component.
Couldn't get the Nu HTML Checker to run. Should be alright though.
> feat: add step indicator component

- src/lib/list-group/ListgroupItem.svelte
Closes #
When a `<ListgroupItem>` is without an `href` inside of `<Listgroup active>`, it is rendered as a `<button>` without a type specified, which means it defaults to `type="submit"`. If the `<Listgroup>` is inside a `<form>`, clicking the item causes the form to submit. This PR adds `type="button"` to the `<ListgroupItem>`
> fix: ListgroupItem button type

- src/lib/accordions/AccordionItem.svelte
Adds `local` modifier to the `Accordion` transistion.
> transition|local

- src/lib/avatar/Avatar.svelte
> fix: remove log message in Avatar Dot

- src/lib/dropdowns/DropdownItem.svelte
Closes #
Adds `type='button'` to `<DropdownItem>` so that if the dropdown is inside a form, it will not submit the form.
> Fix DropdownItem button type

- README.md
- src/routes/extend/flowbite-svelte-blocks.md
- src/routes/extend/flowbite-svelte-starter.md
- src/routes/extend/starters.md
- src/routes/pages/how-to-contribute.md
- tests/extend.spec.ts
- update How to contribute page
- add Codeflow links
- update Flowbite Svelte Starter page
> feat: add Codeflow link

- src/lib/index.ts
- src/lib/toolbar/Toolbar.svelte
- src/lib/toolbar/ToolbarButton.svelte
- src/lib/utils/CloseButton.svelte
- src/lib/utils/MenuButton.svelte
- src/routes/components/card.md
- src/routes/components/dropdown.md
- src/routes/forms/textarea.md
Abstraction of `ToolbarButton`:
- `ToolbarButton` maintains colors
- `CloseButton` is now inherited for `ToolbarButton`
- `MenuButton` added as another inheritance from `ToolbarButton`
- other components and docs updated to use the above
> toolbar abstraction

- src/lib/sidebars/SidebarDropdownWrapper.svelte
- src/routes/components/sidebar.md
Closes #589
- Add TransitionTypes and TransitionParamTypes to SidebarDropdownWrapper.
- Add an example
> feat: add transition to SidebarDropdownWrapper

- src/lib/navbar/NavLi.svelte
Fix for the case when `getContext` returns `undefined` or `null`
> fix: navbar-li undefined

- src/lib/forms/NumberInput.svelte
Closes #594
Events forwarding added to `NumberInput`
> fix: event forwarding for numberinput

- src/app.html
This PR replaces Google Analytics with Fathom Analytics as a privacy-friendly alternative.
> docs: replace Google Analytics with privacy-friendly Fathom

- src/app.html
- src/routes/layouts/component/+page.svelte
- src/routes/layouts/formLayout/+page.svelte
- src/routes/layouts/pageLayout/+page.svelte
- src/routes/layouts/typographyLayout/+page.svelte
- src/routes/layouts/utilitiesLayout/+page.svelte
- static/styles/docs.css
> fix: add carbon

- src/lib/accordions/AccordionItem.svelte
The attribute aria-expanded should be set on the button element instead of the h2 element.
> fix: incorrect aria-expanded in <h2>

- src/routes/examples/snapshot/+page.svelte
> fix: snapshot page update 2

- package.json
- src/routes/pages/faster-compiling-speed.md
This page shows how to set up for faster compilation.
> Faster-compiling speed page

- src/lib/speed-dial/SpeedDial.svelte
- src/routes/components/speed-dial.md
- add color, gradient, shadow, and outline styles props to speed-dial component
> feat: add color, gradient, shadow, and outline props to speed-dial

- src/lib/forms/FloatingLabelInput.svelte
> fix: forward input event

- src/lib/gallery/Gallery.svelte
- src/lib/gallery/GalleryItem.svelte
- src/routes/components/gallery.md
Re factor of `Gallery` component. Some API simplifications.
> Gallery - API simplification

- src/routes/components/gallery.md
Important typo found in `Gallery` docs. Corrected now.
> fix: typo in docs

- src/lib/alert/Alert.svelte
- src/lib/alerts/Alert.svelte
- src/lib/tables/TableHead.svelte
- src/lib/utils/Popper.svelte
- src/routes/components/avatar.md
- src/routes/components/banner.md
- src/routes/components/button-group.md
- src/routes/components/button.md
- src/routes/components/darkmode.md
- src/routes/components/dropdown.md
- src/routes/components/forms.md
- src/routes/components/indicators.md
- src/routes/components/tab.md
- src/routes/components/table.md
- src/routes/components/toast.md
- src/routes/extend/icons.md
- src/routes/forms/input-field.md
- src/routes/forms/search-input.md
- src/routes/forms/textarea.md
- src/routes/pages/how-to-contribute.md
- src/routes/typography/link.md
Ran [typos-cli](https://github.com/crate-ci/typos) on the project after I noticed a couple of minor typos. This change simply corrects the minor typos I found.
> chore: correct some typos

- src/hooks.server.js
Closes #671
Quick and dirty workaround for the redirections issue.
> fix redirections'

- src/hooks.server.js
Correction to quick and dirty redirection hook implemented earlier today.
This version is a bit more compact and more performant.
> feat: slightly shorter version of redirection hooks

- src/routes/utils/ExampleDarkMode.svelte
- src/routes/utils/ExampleWrapper.svelte
Refers to #680 - corrects the dark mode button behavior in examples
> fix: dark-mode in examples

- src/lib/modals/Modal.svelte
- src/routes/utils/ExampleWrapper.svelte
Closes #680
'Edit on GitHub' button now provides a link to appropriate place in GitHub.
> Edit on GitHub link

- src/routes/utils/ExampleWrapper.svelte
Fixes the ExampleWrapper. Initial refresh issue prevented from displaying Edit on GitHub buttons.
> fix: initial refresh fix

- README.md
Closes https://github.com/themesberg/flowbite-svelte/issues/695
This PR updates the thumbnail colors on the README page.
> docs(README): update thumbnails

- src/routes/landing/Components.svelte
- src/routes/landing/Contributors.svelte
- src/routes/landing/DesignFigma.svelte
- src/routes/landing/Featured.svelte
- src/routes/landing/GetStarted.svelte
- src/routes/landing/utils/Section.svelte
Unification of the sections in the home page.
- management of width
- reactive padding
- border divistion
> landing zone - section to unify the big layout

- CONTRIBUTING.md
Changes a few spelling errors in CONTRIBUTING.md
-"In stead" changed to "Instead"
-"Coventional" changed to "Conventional"
-"Make" changed to "Making"
> Spelling corrections

- src/routes/landing/Components.svelte
Components element on the landing page is huge, and requires lots of scrolling.
This PR trims the number of initially visible components to ease the scrolling of the home page, keeping the possibility to show
all of them if user wishes. 
"View all components" button now expands the hidden components instead of being the link to the docs.
> feat: trim number of components

- src/lib/cards/Card.svelte
- src/lib/utils/Frame.svelte
There are more components using the Frame component. If there are requests in the future, we can add them.
Closes #724
Fix the Card component not event-forwarding to the Frame component.
> fix: add event forwarding to Frame component in Card component. 

- src/lib/accordion/Accordion.svelte
- src/lib/alerts/Alert.svelte
- src/lib/cards/Card.svelte
- src/lib/list-group/Listgroup.svelte
- src/lib/modals/Modal.svelte
- src/lib/navbar/Navbar.svelte
- src/lib/popover/Popover.svelte
- src/lib/toasts/Toast.svelte
- src/lib/toolbar/Toolbar.svelte
- src/lib/tooltips/Tooltip.svelte
- src/lib/utils/Frame.svelte
- src/lib/utils/Popper.svelte
Adds typescript support to components that are  `Frame` *subclasses*
- `Frame` props extended to: `<a/>`, `class`
- components inherit props from `Frame` and add their own `export`s
-
> feat: typescript types for frame subclasses

- src/lib/accordion/Accordion.svelte
- src/lib/accordion/AccordionItem.svelte
Closes #721
Border moved from the container to the accordion items.
> fix: accordion gap

- src/lib/timeline/TimelineItem.svelte
- src/lib/utils/focusTrap.js
- src/routes/+page.server.ts
- src/routes/docs/examples/testsnap.svelte
- src/routes/landing/Contributors.svelte
- src/routes/landing/SocialProof.svelte
And few more ts types corrections.
> fix: more ts check corrections

- src/lib/buttons/Button.svelte
Hover on gradient outline button had `group-` modifier. Fixed.
> fix: hover on gradient outline button

- src/lib/accordion/AccordionItem.svelte
Fixing a Typo in AccordionItem.svelte
- [x ] Completed
> fix: Typo in AccordionItem.svelte

- src/lib/buttons/Button.svelte
- src/lib/ratings/Rating.svelte
Closes #744
- add primary to button 
- starUpClass and starDownClass to rating
> fix: add primary to button and starUpClass and starDownClass to rating

- src/lib/types.ts
- src/routes/docs/components/bottom-navigation.md
- src/routes/docs/pages/introduction.md
- src/routes/docs/pages/quickstart.md
- update the introduction page
- update the quickstart page
- change the color to primary on bottom-navigation page
> docs: add primary color and change primary color in bottom-navigation page

- src/routes/docs/components/sidebar.md
Closes #
Since we updated URL, sidebar activeUrl is not working.
Fixed by adding `/docs/components/sidebar`.
> fix: sidebar activeUrl update by adding docs/

- src/routes/docs/pages/introduction.md
- src/routes/docs/pages/quickstart.md
Closes #
- update tailwind.config.cjs
> docs: update tailwind.config.cjs 

- src/lib/popover/Popover.svelte
- src/lib/tooltips/Tooltip.svelte
- src/lib/utils/Popper.svelte
- src/routes/docs/components/tooltip.md
Correction to `Tooltip`:
- `style` replaced by `type` in docs
- `Popper` arrow - now with not class depending on `flowbite.css`
> fix: tooltip style

- src/lib/alerts/Alert.svelte
Closes #757
Correction to `Alert` props declaration for Typescript.
> fix: alert props

- src/lib/tables/TableBodyCell.svelte
- src/lib/tables/TableHeadCell.svelte
- src/routes/docs/components/table.md
- src/routes/testdir/+page.svelte
Closes #
- add events to TableHeadCell and TableBodyCell
- add table sort example to https://flowbite-svelte.com/docs/components/table
> feat: add events to tableheadcell and tablebodycell components

- src/lib/buttons/Button.svelte
- src/lib/buttons/GradientButton.svelte
- src/lib/index.ts
- src/lib/speed-dial/SpeedDial.svelte
- src/lib/speed-dial/SpeedDialButton.svelte
- src/routes/docs/components/button.md
Closes #764 
Modifications to `Button`.
- Gradient buttons use completely unique color palette, so mixing them with normal buttons is a nightmare for types. I have now extracted those to `GradientButton`. 
- Re-implemented gradient outline to fix the resizing issue
> Gradient button

- src/lib/ratings/Rating.svelte
- src/routes/docs/components/rating.md
- bug fix for Rating component
> fix: rating component update

- src/lib/buttons/GradientButton.svelte
- src/lib/darkmode/DarkMode.svelte
- src/routes/docs/components/darkmode.md
User can add `initialTheme='dark'`
> feat: add initialTheme to DarkMode component

- src/lib/device-mockup/Android.svelte
- src/lib/device-mockup/Default.svelte
- src/lib/device-mockup/DeviceMockup.svelte
- src/lib/device-mockup/Ios.svelte
- src/lib/device-mockup/SmartWatch.svelte
- src/lib/device-mockup/Tablet.svelte
- src/lib/index.ts
- src/routes/docs/components/device-mockups.md
- src/routes/props/DarkMode.json
- src/routes/props/DeviceMockup.json
- src/routes/props/Rating.json
- tests/components.spec.ts
Closes #777 #775
- add DeviceMockup component
> feat: devicemockup

- .github/ISSUE_TEMPLATE/bug_report.yml
- src/lib/modals/Modal.svelte
- src/routes/docs/components/modal.md
- src/routes/testdir/+page.svelte
> fix: typo and update bug_report.yml

- src/routes/docs/examples/sidebar-layout.md
Svete -> Svelte
Closes #
Changed Svete to Svelte
> Fix spelling error in sidebar-layout.md

- src/lib/modals/Modal.svelte
A [patch](https://github.com/themesberg/flowbite-svelte/pull/780#issuecomment-1559115126) fix
> fix: modal update

- .gitignore
- CHANGELOG.md
- src/lib/forms/Checkbox.svelte
- src/lib/forms/Toggle.svelte
- src/routes/docs/forms/toggle.md
- src/routes/props/Banner.json
- src/routes/props/BottomNav.json
- src/routes/props/BottomNavHeader.json
- src/routes/props/BottomNavHeaderItem.json
- src/routes/props/BottomNavItem.json
- src/routes/props/Smartwatch.json
- src/routes/props/Tablet.json
- src/routes/props/Toggle.json
Closes #794
- add custom size to toggle
- add the default value on to checkbox
> Toggle and checkbox default value update 

- src/lib/utils/Frame.svelte
Closes #790
`$$restProps.color` may send `undefined` to underlying `Frame`.
> fix: issue #790

- src/lib/modals/Modal.svelte
- src/routes/docs/components/modal.md
Closes #786
- Correction to the inner frame width.
- Removal of unnecessary `id` attrs in `Modal` docs.
> fix: issue 786

- src/lib/list-group/Listgroup.svelte
- src/lib/list-group/ListgroupItem.svelte
- src/routes/docs/components/list-group.md
Closes #534 
- Typescript support for `let:item` in the `Listgroup` component.
- Minor tweaks to docs
> fix: #534 list group typing

- src/lib/utils/Popper.svelte
Closes #781 
Support for the two words placement for arrow: `top-end`, `left-start`, etc.
> fix: #781 tooltip arrow

- src/lib/index.ts
- src/lib/utils/focusTrap.js
Closes #783
Tabbable check done at each key press instead of only at the init.
> fix: issue783

- package.json
Having peerDependencies creates unnecessary installation problems.
> fix: remove peerDependencies

- src/lib/darkmode/DarkMode.svelte
Addresses #782 
This should cause no flicker, but I have removed the `initialTheme`.
> fix: darkmode flicker

- src/lib/dropdowns/Dropdown.svelte
> fix: issue812

- src/lib/toasts/Toast.svelte
- src/routes/docs/components/toast.md
Toast updates
- some code polishing
- removal of `<slot name='extra'>`
- added prop `align: boolean = true`
> toast simplification

- src/lib/alerts/Alert.svelte
- src/routes/props/Alert.json
> Change alert hard classes to export

- src/routes/utils/ExampleWrapper.svelte
> Remove border radius of code wrapper

- src/lib/alerts/Alert.svelte
- src/routes/docs/components/alert.md
Appendix to the `Alert` component - support for the transitions.
> alert - transition added

- src/lib/popover/Popover.svelte
- src/lib/utils/Popper.svelte
Closes #839 
This should address the issues reported at #839. 
Extra feature is the border on the popover arrow element.
Please do test it out.
> popover - bg and border

- src/routes/docs/typography/heading.md
Closes #
Fix prop name for span decoration classes in docs
> Fix prop name for span decoration classes in docs

- package.json
- pnpm-lock.yaml
- src/routes/+layout.svelte
- static/styles/docs.css
> feat: add search on home page

- src/lib/utils/ChevronUp.svelte
- src/routes/docs/components/avatar.md
- src/routes/docs/components/button-group.md
Fix the thickness of ChevronUp svg icon.
> fix: chevronup thickness

- src/lib/forms/Checkbox.svelte
- src/lib/forms/Radio.svelte
- src/lib/toolbar/ToolbarGroup.svelte
- src/routes/docs/components/button-group.md
- src/routes/docs/components/card.md
- src/routes/docs/components/darkmode.md
- src/routes/docs/components/drawer.md
- src/routes/docs/components/dropdown.md
- src/routes/docs/components/footer.md
- src/routes/docs/forms/checkbox.md
- src/routes/docs/forms/file-input.md
- src/routes/docs/forms/floating-label.md
- src/routes/docs/forms/input-field.md
- src/routes/docs/forms/radio.md
- src/routes/docs/pages/colors.md
- src/routes/docs/pages/compiler-speed.md
- src/routes/docs/pages/customization.md
- src/routes/docs/pages/introduction.md
- src/routes/docs/pages/typescript.md
- src/routes/docs/utilities/label.md
- src/routes/docs/utilities/toolbar.md
- tests/page.spec.ts
Closes #
- Checkbox
- Radio
- ToolbarGroup
- button-group
- card
- darkmode
- drawer
- dropdown
- footer
- checkobx
- file-input
- floating-label
- input-field
- radio
- label
- toolbar
> refactor: twMerge class update

- src/routes/docs/pages/customization.md
Add the "Global customization" section.
> docs: update customization page

- src/lib/megamenu/MegaMenu.svelte
- src/lib/ratings/AdvancedRating.svelte
- src/routes/docs/components/accordion.md
- src/routes/docs/components/alert.md
- src/routes/docs/components/avatar.md
- src/routes/docs/components/badge.md
- src/routes/docs/components/button-group.md
- src/routes/docs/components/darkmode.md
- src/routes/docs/components/drawer.md
- src/routes/docs/components/footer.md
- src/routes/docs/components/forms.md
- src/routes/docs/components/indicators.md
- src/routes/docs/components/kbd.md
- src/routes/docs/components/list-group.md
- src/routes/docs/components/mega-menu.md
- src/routes/docs/components/modal.md
- src/routes/docs/components/navbar.md
- src/routes/docs/components/rating.md
- src/routes/docs/components/sidebar.md
- src/routes/docs/components/timeline.md
- src/routes/docs/forms/toggle.md
Update: 
- MegaMenu
- Rating
- indicator
- kbd
- list-group
- mega-menu
- modal
- navbar
- rating
- sidebar
> docs: update up to sidebar components

- src/lib/forms/MultiSelect.svelte
Closes (https://github.com/themesberg/flowbite-svelte/issues/864)
Bind multi-select value to arrays of value
> fix: Bind multiselect value to arrays of value

- src/lib/typography/Hr.svelte
- src/routes/docs/typography/blockquote.md
- src/routes/docs/typography/heading.md
- src/routes/docs/typography/hr.md
- src/routes/docs/typography/link.md
- src/routes/docs/typography/list.md
- src/routes/docs/typography/paragraph.md
- src/routes/utils/CopyCliboardInput.svelte
Update props description on the following pages:
- hr
- blockquote
- heading
- link
- list
- paragraph
> docs: update props descriptions

- src/lib/megamenu/MegaMenu.svelte
Fix: `item` type recognition by typescript in `MegaMenu`
> fix: ts item type in megamenu

- src/lib/utils/Frame.svelte
- src/lib/utils/Popper.svelte
`null_transition` used instead of `noop`. That prevents the usage of built in fade animation when defocusing tooltip.
> Frame transition fix

- src/routes/docs/extend/icons.md
- tests/extend.spec.ts
This PR updates the Svelte Icons page to use Flowbite Icons & also improves the documentation text.
> Icons page

- src/routes/docs/forms/radio.md
Fix radio docs component styles
> docs(radio): fix radio docs component styles

- src/lib/forms/Checkbox.svelte
- src/lib/forms/Radio.svelte
- src/lib/forms/Toggle.svelte
Closes #
Fixes a mistake in applying `$$props.class` in `Radio`,  `Checkbox` and `Toggle`.
> fix: $$props.class

- src/lib/forms/MultiSelect.svelte
- src/routes/docs/forms/select.md
Closes https://github.com/themesberg/flowbite-svelte/issues/864
> fix(multi-select): pre-select values fix

- src/routes/docs/components/forms.md
> Minor correction in documentation

- src/lib/darkmode/DarkMode.svelte
Change to the initial mode choice:
- if explicitly set in `localStorage` - force the mode
- if only browser preference - switch to dark if preferred
- if no browser preference do nothing - respect the author's preset
> fix: initial dark mode

- src/routes/docs/components/accordion.md
Closes #900 
Added example of nesting accordion
> docs: nesting accordion

- src/lib/forms/Dropzone.svelte
- src/routes/docs/forms/file-input.md
> fix(dropzone): fixes dragging file over the input

- src/routes/docs/components/tooltip.md
Related to #935 
Updated documentation to use `type` property for `Tooltip` instead of `style`.
> fix: docs typo - tooltip type

- src/lib/utils/Popper.svelte
- src/routes/docs/components/popover.md
- src/routes/docs/components/tooltip.md
Closes #966
Added option to set the external reference for the popup elements.
Docs updated with two new examples: external reference for `Tooltip` and `Popover`
> feat: #966

- src/routes/docs/forms/checkbox.md
Adding `Checkbox` custom color example after having discussion on discord.
> docs: custom color

- src/lib/bottom-nav/BottomNav.svelte
- src/lib/bottom-nav/BottomNavItem.svelte
- src/lib/dropdowns/Dropdown.svelte
- src/lib/dropdowns/DropdownItem.svelte
- src/lib/navbar/NavLi.svelte
- src/lib/navbar/NavUl.svelte
- src/lib/sidebars/Sidebar.svelte
- src/lib/sidebars/SidebarItem.svelte
- src/routes/+layout.svelte
- src/routes/docs/+layout.svelte
- src/routes/docs/components/bottom-navigation.md
- src/routes/docs/components/dropdown.md
- src/routes/docs/components/navbar.md
- src/routes/docs/components/sidebar.md
#988 #986
- BottomNav components
- Sidebar components
- Dropdown components
- Navbar components
Shorten expression:
From:
```
<BottomNav position="absolute" classInner="grid-cols-4" >
<BottomNavItem btnName="BottomNav" active={activeUrl === '/docs/components/bottom-navigation'}>
<Icon name="adjustments-vertical-outline" class={activeUrl === '/docs/components/bottom-navigation' ? svgActiveClass : svgClass} />
</BottomNavItem>
```
to:
```
<BottomNav position="absolute" classInner="grid-cols-4" {activeUrl}>
<BottomNavItem btnName="BottomNav" href="/docs/components/bottom-navigation">
<Icon name="adjustments-vertical-outline" />
</BottomNavItem>
// more lines
```
> feat: bottomnav components update

- CHANGELOG.md
- src/lib/bottom-nav/BottomNav.svelte
- src/lib/bottom-nav/BottomNavItem.svelte
- src/lib/dropdowns/Dropdown.svelte
- src/lib/dropdowns/DropdownItem.svelte
- src/lib/navbar/NavLi.svelte
- src/lib/navbar/NavUl.svelte
- src/lib/sidebars/Sidebar.svelte
- src/lib/sidebars/SidebarItem.svelte
- src/lib/toasts/Toast.svelte
- src/routes/docs/+layout.svelte
- src/routes/docs/components/bottom-navigation.md
- src/routes/docs/components/navbar.md
- src/routes/docs/components/sidebar.md
- src/routes/props/BottomNav.json
- src/routes/props/BottomNavItem.json
- src/routes/props/Dropdown.json
- src/routes/props/DropdownItem.json
- src/routes/props/NavLi.json
- src/routes/props/NavUl.json
- src/routes/props/Sidebar.json
- src/routes/props/SidebarItem.json
Closes #981
Add add missing primary to Toast interface $$Props
> fix: add primary to Toast interface $$Props

- .github/workflows/playwright-and-lint.yaml
> fix: playwright-and-lint.yaml update test:integration

- postcss.config.cjs
- src/lib/alerts/Alert.svelte
- src/lib/badges/Badge.svelte
- src/lib/banner/Banner.svelte
- src/lib/dropdowns/Dropdown.svelte
- src/lib/forms/MultiSelect.svelte
- src/lib/modals/Modal.svelte
- src/lib/toasts/Toast.svelte
- src/lib/types.ts
- src/routes/docs/components/badge.md
- src/routes/docs/components/modal.md
- src/routes/docs/components/toast.md
- src/routes/docs/forms/select.md
- src/routes/props/Modal.json
- src/routes/props/Toast.json
Closes #975
Unification of the behaviour for *dismissable* components: `Alert`, `Badge`, `Banner`, `Modal`, `Toast`.
All those now dispatch `open` and `close` event.
> unification of dismissables

- src/routes/docs/forms/input-field.md
> fixed a typo in input field docs

- src/routes/docs/pages/quickstart.md
> docs: update quickstart

- src/routes/+layout.svelte
- src/routes/layouts/component/+page.svelte
> fix: ads position since it does not show unless you refres the browser

- src/lib/badges/Badge.svelte
- src/lib/modals/Modal.svelte
- src/routes/docs/components/modal.md
> Modal update

- src/lib/breadcrumbs/Breadcrumb.svelte
- src/lib/carousels/Carousel.svelte
- src/lib/carousels/Thumbnails.svelte
- src/lib/darkmode/DarkMode.svelte
- src/lib/paginations/Pagination.svelte
- src/lib/sidebars/Sidebar.svelte
Closes #964
change hard-coded aria-label to export
> fix: #964 change export ariaLabel

- src/lib/carousels/Carousel.svelte
- src/lib/carousels/Slide.svelte
- src/routes/docs/components/carousel.md
Closes #899
Add `href` for `Carousel` images.
> feat: href for carousel

- src/routes/docs/pages/faq-and-tips.md
Closes #990 #922
Add how to purge css files in the faq-and-tips page.
> feat: add faq-and-tips.md and add how to purge CSS files

- src/routes/docs/pages/faq-and-tips.md
Thanks for checking out `vite-plugin-tailwind-purgecss`! I noticed that the install instruction for it was missing the plugin import so I went ahead and fixed it 😄.
> docs: fixed `vite-plugin-tailwind-purgecss` install instructions

- src/lib/forms/MultiSelect.svelte
- src/lib/forms/Select.svelte
- src/lib/types.ts
> feat: add <T> to SelectOptionType and update Select and MultiSelect

- src/lib/utils/Popper.svelte
> fix: removeEventListener in onDestroy

- src/lib/alerts/Alert.svelte
Closes #1056 
Fix: add back the missing horizontal margin
> fix: add -mx-1.5 to alert

- src/lib/avatar/Avatar.svelte
- src/lib/avatar/Placeholder.svelte
Closes #1064
Safari does not display correctly `svg` objects without width/height set (or set to `auto`).
Needed to hard code sizes.
> fix: avatar placeholder safari

- src/routes/docs/forms/input-field.md
Closes https://github.com/themesberg/flowbite-svelte/issues/1072
Fix pattern example in input field docs page, the issue is related to svelte template engine that interpret curly braces as javascript and and resolves them. Therefore, if you write `[0-9]{3}`, it renders as `[0-9]3`, the solution is to pass string to `pattern` attribute.
Example on how to escape curly braces in svelte
Example https://svelte.dev/repl/2290fc67e7c0479881a266abb34e0f4d?version=3.20.1
> docs: fix input field example tel pattern

- src/lib/forms/MultiSelect.svelte
This added `on:change` and `on:input` methods to Multiselect so its behavior mirrors that of Select
> feat: add on:change and on:input to multiselect

- src/routes/docs/pages/introduction.md
- src/routes/docs/pages/quickstart.md
- src/routes/landing/Hero.svelte
- src/routes/utils/CopyCliboardInput.svelte
Closes #1028 ?
although I didn't close it as it appears someone else closed it before a change was made?
CopyClipboardInput.svelte, introduction.md and quickstart.md have different installation instructions.
I am not sure if there was already a pr that is wip for this change but I thought I create a pr to confirm if the changes are valid/acceptable.
The resulting change to the command in CopyClipboardInput.svelte makes the command a bit long so I changed the min-width of the input in CopyClipboardInput.svelte and Hero.svelte's gap-10 to gap-8.
I wanted to clarify the instruction and I am basing the changes on 
`https://github.com/shinokada/flowbite-svelte-starter/blob/main/package.json`
which has both `flowbite-svelte` and `flowbite` as devDependencies meaning that the instructions should …
> docs: change installation cmd, change gap and minwidth

- src/routes/docs/plugins/charts.md
[Closes #1095](https://github.com/themesberg/flowbite-svelte/issues/1095)
Fix the issue on chart example ( ipad / iphone )
> docs: fix chart issue in ipad/iphone

- src/lib/indicators/Indicator.svelte
- src/routes/component-data/Indicator.json
[Closes #1114](https://github.com/themesberg/flowbite-svelte/issues/1114)
> fix indicator placement type

- src/routes/+layout.svelte
Fix the navbar button not display on Ipad
now
after
> fix the navbar not visible on ipad

- src/routes/+layout.svelte
Closes [#1124](https://github.com/themesberg/flowbite-svelte/issues/1124)
fix navBar flowbite site
> fix navbar site

- .github/workflows/playwright-and-lint.yaml
- package.json
- pnpm-lock.yaml
- src/lib/forms/FloatingLabelInput.svelte
- src/routes/component-data/FloatingLabelInput.json
- src/routes/docs/forms/floating-label.md
- src/routes/utils/CarbonAds.svelte
- svelte.config.js
> Server fix

- src/lib/navbar/NavHamburger.svelte
- src/routes/+layout.svelte
- src/routes/component-data/NavHamburger.json
Closes [#1772820280](https://github.com/themesberg/flowbite-svelte/pull/1122#issuecomment-1772820280)
Fix navbar mobile, now open the sidebar on mobile view
> fix sidebar navbar menu

- src/lib/datepicker/Datepicker.svelte
- src/lib/footer/Footer.svelte
- src/lib/toolbar/Toolbar.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/component-data/Footer.json
- src/routes/utils/CompoAttributesViewer.svelte
- src/routes/utils/Footer.svelte
- src/routes/utils/GitHubCompoLinks.svelte
- src/routes/utils/MetaTag.svelte
- src/routes/utils/helpers.ts
- src/routes/utils/icons/OperaWallet.svelte
- src/routes/utils/mdsvex.d.ts
Closes [#483](https://github.com/themesberg/flowbite-svelte/issues/483)
- fix some typescript error
is this file `/src/routes/utils/Paging.svelte` used? because I see that  is imported into this page `src/routes/layouts/component/+page.svelte` but if I open the page https://flowbite-svelte.com/layouts/component it doesn't work
> fix some types error

- src/routes/docs/components/dropdown.md
> docs: removal of classUl from docs

- src/lib/forms/MultiSelect.svelte
`Multiselect` refactored
- simplified implementation
- `selected` event changed to `change` and `input` as in standard select
- corrected select size for cases when nothing selected
> refactor for smiplification

- src/lib/utils/Popper.svelte
Closes #1131 
Adds the list of Flowbite-UI middlewares as exported prop.
> middlewares as export

- README.md
Fix Tabs component page url.
Fix Tabs component name ( based on [the original flowbite](https://github.com/themesberg/flowbite)).
> docs: fix tabs component name and link

- src/lib/darkmode/DarkMode.svelte
- src/routes/docs/components/darkmode.md
- src/routes/utils/ExampleWrapper.svelte
Closes #1157
`DarkMode` changed:
- recognizes if within `iFrame`
- sets `class="dark"` to local document
- writes to `localStorage` only if not in `iFrame`
Minor changes to docs.
> fix: #1157

- src/lib/forms/Input.svelte
Closes #1189 
Correction to input padding - vertical.
> fix in vertical padding

- src/lib/carousel/Carousel.svelte
Closes #1188 
Correction to looping when last image displayed.
> fix carousel loop last image

- src/routes/docs/forms/input-field.md
The input was probably copy-pasted from the "success" input above, but the id and placeholder weren't updated. Now the id and placeholder match with the label and Helper message.
> docs: update copy-pasted input in Validation section of input-field

- src/lib/toolbar/Toolbar.svelte
Fixes to `Toolbar`:
- `color` inherited from underlying `Frame`
- padding corrections
- typescript props corrections
> fixes to toolbar

- src/lib/mega-menu/MegaMenu.svelte
> ts fixes for mega-menu

- src/lib/cards/Card.svelte
- removal of the hard coded max size for horizontal card
- typo correction
> card horizontal size fix

- src/lib/cards/Card.svelte
- src/routes/docs/components/card.md
Tweaks to card sizing:
- added 'none' to 'size' 
- size 'md' from 'max-w-lg' to 'max-w-xl'
> card size none

- src/lib/forms/Dropzone.svelte
Closes #1244
Add click handler to Dropzone button, so whole button is clickable.
I tried putting a on:click handler on the button first while still having the label and input nested inside it, but this only resulted in the click handler on the button being called twice and the one on the input not being called. So I moved the label and input outside the button and then it worked.
This might well be because labels aren't allowed inside button elements according to the html specs.
"[Content model](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model): [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), but there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant and …
> Add click handler to Dropzone button, so whole button is clickable.

- src/lib/utils/TransitionFrame.svelte
Closes #1225
This PR fixes a bug in the `TransitionFrame` component, if the component was not `dismissable` a check was missing if it was open.
I also removed the `close` prop because I don't think it's necessary when it's not `dismissable`. For more context, read the issue.
> fix: add if statement to `TransitionFrame` component

- .github/workflows/playwright-and-lint.yaml
- package.json
Closes #
I saw that you had to update the PNPM version within the workflow file in a recent commit, which is no longer required if you specify PNPM in the package.json
Doing this change I took the liberty to update the CI from node 18 to 20 and remove the custom cache setup, which should already be handled by the setup-node task.
> Improve ci setup

- src/routes/docs/components/table.md
I am just adjusting the table docs to match the types
> docs: fix table.md

- src/lib/table/TableBodyRow.svelte
Closes #
missing border in light mode for TableBodyRow
> missing border in light mode for TableBodyRow
